MaelstromMusic = MaelstromMusic or {}
MaelstromMusic.MOD_ID = "maelstromsmusic"
MaelstromMusic.RADIOS_DIR = "media/radios"
MaelstromMusic.TVS_DIR = "media/televisions"
MaelstromMusic.BACKGROUNDS_DIR = "media/backgrounds"
MaelstromMusic.MAINMENU_DIR = "media/mainmenu"
MaelstromMusic.FREQ_STEP = 200
MaelstromMusic.Scanner = MaelstromMusic.Scanner or {}
MaelstromMusic.Playback = MaelstromMusic.Playback or {}
MaelstromMusic.Ambience = MaelstromMusic.Ambience or {}
MaelstromMusic.Addons = MaelstromMusic.Addons or {}
